safe: true
exclude: [README.md]
paginate: 2
siteurl: 'http://gloria-studio.by/'
media: /img/

markdown: kramdown

prose:
  media: /img/

locales:
  ru:
    gloria: Глория
    latest_news: Последние новости
    all_news: Все новости
    news: Новости
    gallery: Галлерея

  en:
    gloria: Gloria
    latest_news: Latest news
    all_news: All news
    news: News
    gallery: Gallery
