safe: true
exclude: [README.md]
paginate: 2

locales:
  ru:
    latest_news: Последние новости
    all_news: Все новости
    news: Новости
    gallery: Галлерея

  en:
    latest_news: Latest news
    all_news: All news
    news: News
    gallery: Gallery
