safe: true
exclude: [README.md]
paginate: 2

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "smart"]

locales:
  ru:
    gloria: Глория
    latest_news: Последние новости
    all_news: Все новости
    news: Новости
    gallery: Галлерея

  en:
    gloria: Gloria
    latest_news: Latest news
    all_news: All news
    news: News
    gallery: Gallery
